### ISSUE TITLE
Странное поведение streaming orderbook

### ISSUE THREAD

**Issue by finico** [Tinkoff/invest-openapi#118]
Анализировал логи и заметил, что иногда streaming orderbook очень странно себя ведет.

Ссылка на 10 минут из лога по WDC за 2020-01-30 (17:30 - 17:40 по МСК)
https://gist.github.com/finico/a9df5b36fa649299047a18c77a74d3ef

Такое встречается и на других бумагах.

Суть проблемы:

С момента официального открытия работает нормально.
Спустя примерно 5 минут, с момента 2020-01-30T14:34:38.167Z (строка 994) стакан "залипает" и по бидам и по аскам около спреда (по дальним изменения иногда есть)
При этом candles все правильно присылает
Это длится до 2020-01-30T14:37:18.527Z (строка 1387) - почти 3 минуты

Самое интересное, что такое состояние стакана было в 2020-01-30T14:33:46.875Z (строка 747), потом он минуту менялся и вдруг вернулся к этому состоянию

Я не эксперт, но стакан первичен и свечи не могут пройти от low 64.81 до high 66.56 без изменения спреда.

PS лог пишется сразу на message от websocket, до каких-либо манипуляций
Если нужны логи по другим бумагам, могу прислать, но, надеюсь, что они у вас и так есть

**Comment by necryin** [comment]
Я правильно понимаю что вас смущает что свеча шире по значениям чем стакан?

**Comment by finico** [comment]
@necryin, смущает, что вот эти 3 минуты, которые я выделил на картинке, стакан практически стоял на месте

<img width="247" alt="Screen Shot 2020-02-12 at 17 57 09" src="https://user-images.githubusercontent.com/4924283/74346919-54812c80-4dc1-11ea-933a-97a60086cf96.png">

**Comment by ddmrtc** [comment]
довольно часто бывает что через streaming приходят "залипшие" данные, т.е. данные приходят, но они данные не меняются, при этом в приложении в то же время меняются часто, могу так же насобирать логов 
подписываюсь на глубину 1

**Comment by necryin** [comment]
@finico  @ddmrtc Напишите в саппорт, пожалуйста. Так же надо знать какой библиотекой пользуетесь для подключения к стриму. И если есть возможность попробуйте из под другого провайдера подключиться. Если из плохой связи клиенту от сервера перестанут поступать сообщения то он и не узнает о разрыве соединения.

**Comment by finico** [comment]
@necryin Вы приложенные логи смотрели?
Прочтите первоначальное описание проблемы, пожалуйста, там все подробно написано.
Соединение не разрывается. Данные идут, но они неверные.

API с таким багом является очень нестабильным и может привести с убыткам.

Библиотека для node - ws (SDK никакой не пользуюсь).

**Comment by necryin** [comment]
@finico В любом случае напишите в сапорт, от них придет уже информация чтобы можно было по логам посмотреть. Будет огромным плюсом если вы скините еще примеры свежих логов с такой ситуацией, оперативные логи по стакану мы можем посмотреть только за текущий день

**Comment by deniro98** [comment]
@finico Я сам столкнулся с данной проблемой, но со стороны участника, который неспециально влияет на Low/High, когда сам стакан может и не меняется (глубина спреда)

История такая, API действительно часто может выдавать неверный стакан, но даже если стакан верный, и кто-то сделает покупку в стакане, но не из "краев" спреда, то Low/High, Open/Close  может изменится, а стакан при этом с глубиной, например в 5, будет неизменным. Это с одной стороны ошибка, что можно выполнить заявки минуя заявки в стакане, с другой стороны непонятно.

**Comment by e673** [comment]
И такая проблема у меня тоже постоянно наблюдается. Пытаюсь строить график как по текущей цене, так и по средней величине между ценой покупки и продажи по списку заявок. И иногда стакан залипает: в течение 10-15 секунд заявки залипают, а движуха происходит где-то в глубине.

При этом:
1. Переподключение проблему не решает - приходят те же данные.
2. В приложении и в терминале на сайте стакан другой и больше похож на правдоподобный.

Если поймаю такую ситуацию утром - попробую написать в саппорт для отладки.

**Comment by lolpoi** [comment]
Всё гораздо хуже.

AAPL за вчера:

https://gist.github.com/lolpoi/45e2e8f98195a9ade5bc36e808d123fd

06:26:18 (UTC) -- старт лога.

Почти 10 минут стакан не приходил, а потом прорвало (остальное вырезано, там много).
И обратите внимание когда instrument_info пришёл с открытием торгов.

Это всё абсолютно неюзабельно.
Да, ввели время в стриминг. Но что мне толку от серверного времени? За какое время стакан? В свечах хотя бы есть своё время ещё.

В саппорт напишу, да.

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, рекомендуем переходить на новый api -  https://github.com/Tinkoff/investAPI/
