### ISSUE TITLE
Стоп заявки

### ISSUE THREAD

**Issue by cia76** [Tinkoff/invest-openapi#145]
Для полноценной автоторговли, пожалуйста, реализуйте механизм постановки стоп заявок. Не всегда можно обойтись лимитными и рыночными заявками.

**Comment by vitalyisaev2** [comment]
Не совсем понятно, как вообще предлагается торговать без стоп-лоссов?

**Comment by ElisDN** [comment]
И желательно чтобы были редактируемыми.

**Comment by NikitaMelnikov** [comment]
Стопы можно реализовать самостоятельно, в ОпенАпи не появится функциональность. которой нет в мобильном приложении.
Так что редактирование стопов появится не раньше, чем там

**Comment by ColCh** [comment]
@NikitaMelnikov но ведь стопы есть в мобильном приложении. Стоп-лимиты, но всё же есть. И редактировать их в мобильном приложении можно

**Comment by ogronome** [comment]
Учитывая качество работы всего Тинькова - когда в опредленной акции начинается активность выше среднего, и моб приложение, и вебтерминал могут час-два не показывать ни цену покупки (при покупке по рыночной цене) ни списка операций. Соответственно, stop-loss в api это musthave фича. Говорить "реализуйте сами на клиенте" может говорить только человек, который сам не торгует.

**Comment by NikitaMelnikov** [comment]
@ColCh стоп-заявки в OpenApi будут, просто пока что не могу назвать дату и релиз, в котором они пойдут

**Comment by vitalyisaev2** [comment]
@NikitaMelnikov спасибо, это обнадёживает, потому что для меня отсутствие стоп-заявок это главной блокер для активной торговли.

**Comment by ColCh** [comment]
@NikitaMelnikov конечно. no hassle :) молча ждём. видел тикет в uservoice по теме трейлингов - похоже на то, что они выкатятся одновременно.

**Comment by IvanAgafonov** [comment]
Если тут учитываются комменты, то по-моему мнение стоп-лосс и тейк-профит сейчас must have  для API

**Comment by NikitaMelnikov** [comment]
@IvanAgafonov комменты учитываются :)

**Comment by mlshvdv** [comment]
Есть ли примерные сроки по внедрению стоп-лоссов? Оооочень нужно. Благодарю.

**Comment by NikitaMelnikov** [comment]
Пока что нет

**Comment by denislukinykh** [comment]
+ к внедрению стопов

**Comment by IvanAgafonov** [comment]
@NikitaMelnikov 

> в ОпенАпи не появится функциональность. которой нет в мобильном приложении.

То есть вы будете реализовать только функциональность из мобильного приложения, не смотря на терминал? К примеру создание отложенных заявок на покупку/продажу уже существует в терминале (объеденины с Стоп-лосс и Тейк-профит заявками), но в мобильном приложении так до сих пор не появились. Это значит, что мне надо ждать, пока отложенные заявки появятся в мобильном приложении, а потом только ждать их в API? 

У вас тогда получается IOS, Android, Терминал, API - каждая команда сама по себе?

**Comment by NikitaMelnikov** [comment]
> в ОпенАпи не появится функциональность. которой нет в мобильном приложении.

@IvanAgafonov будет правильней сказать "не появится функциональность, которой нет в брокере"
Если функциональность есть на одной из платформ: web, mobile, терминал, то можно делать и в OpenApi

> У вас тогда получается IOS, Android, Терминал, API - каждая команда сама по себе?

Функциональность может быть разная, команды разные, но вектор развития один

**Comment by victordoshenko** [comment]
Есть ли новости по стоп-заявкам?

**Comment by nightphobos** [comment]
Очень не хватает этого функционала. Приходится вручную ежедневно стоп-лоссы обновлять.

**Comment by matrozov** [comment]
@NikitaMelnikov Добрый день, есть прогнозы по внедрению?

**Comment by nleo** [comment]
+++

Сейчас нет GTC-заявок, но их можно эмулировать через SL/TP в терминале.

Теперь допустим я хочу сделать бота, которыйт торгует акциями по уровням. Есть акции, которые ходят по уровням я хочу заране раставить заявки на покупку/продажу, сейчас мне приходится делать это руками. Если бы SL/TP был в апи и работал как в терминале я мог бы раз в неделю запускать скрипт, который бы смотрел где, что купилось/продалось, где какие заявки надо выставить заново.

SL/TP удобен ещё и тем, что в отличие от рыночной заявки заранее не замораживает средства.

**Comment by nleo** [comment]
Я уже думаю о том, чтобы reverse engeniring терминала или мобильного делать, чтобы иметь возможность работать со SL/TP. Есть подозрение, что это будет сильно быстрее чем ждать пока Тинькофф родит.

**Comment by matrozov** [comment]
> Я уже думаю о том, чтобы reverse engeniring терминала или мобильного делать, чтобы иметь возможность работать со SL/TP. Есть подозрение, что это будет сильно быстрее чем ждать пока Тинькофф родит.

Да тут уже и о смене брокера задумаешься. Ибо кажется, что апи просто заморозилось в какой то момент.

**Comment by vitalyisaev2** [comment]
Вопрос лишь в том, к какому другому брокеру идти. Вроде у Алора есть Open
API со стоп заявками... Но непонятно, стриминговое ли оно, рассылает ли
пуши, или надо самому их поллить, где взять примеры работы и т. п. У
Тинькова, во всяком случае на Go, пример работы очень хороший, что
облегчает вхождение.

ср, 14 окт. 2020 г. в 15:31, Oleg Matrozov <notifications@github.com>:

**Comment by kitMP** [comment]
> > Я уже думаю о том, чтобы reverse engeniring терминала или мобильного делать, чтобы иметь возможность работать со SL/TP. Есть подозрение, что это будет сильно быстрее чем ждать пока Тинькофф родит.
> 
> Да тут уже и о смене брокера задумаешься. Ибо кажется, что апи просто заморозилось в какой то момент.

По-моему api просто померло. Обнов и устранения ошибок нет. В терминале человеческий расчёт средней уже полгода не могут прикрепить...

**Comment by ogronome** [comment]
Алор что-то слишком подворотный вариант.

У Финама есть некий монстр из прошлого в виде DLLки ) сам брокер работает на порядок стабильнее тинькоф, но их решение просто ужасно, если хочется на линуксе и современном языке робота сделать.

У большинства брокеров вообще глухо....

**Comment by vitalyisaev2** [comment]
А как вообще работают компании, которые занимаются HFT? В какие API они ходят?

**Comment by neshkeev** [comment]
Мне сложно понять, почему протянуть REST API до функции, которая установит stop loss/take profit на столько сложно, что этот тикет так долго открыт. Я не знаю какую там архитектуру сделали, но презентационный слой (независимо монолит или микросервисы) обычно общается со слоем сервисов напрямую, поэтому реализация должна быть тривиальной

**Comment by NikitaMelnikov** [comment]
Мы работаем над новой версией API, в которой учтем запросы на функциональность

**Comment by ColCh** [comment]
@NikitaMelnikov 
лучи добра, парни! на текущей версии очень сложно сделать что-то адекватное.

**Comment by moscowpilot** [comment]
а новый API будет поддерживаться в @tinkoff/invest-openapi-js-sdk?
и есть ли примерные сроки?

**Comment by NikitaMelnikov** [comment]
@moscowpilot мы будем предоставлять SDK из коробки для OpenApi v2, сроков пока что нет

**Comment by newyorrker** [comment]
@NikitaMelnikov, в одном из _issues_ видел сообщения про roadmap, он будет опубликован?

**Comment by Dimantchick** [comment]
Шёл март.... Присоединяюсь. Основной необходимый функционал - сл с тп и операции по стриму.

**Comment by bikbulat2** [comment]
Да-да, очень нужны Лосы и Профиты

**Comment by AlexanderVolkovTCS** [comment]
Сейчас SL/TP еще нет, но лимиты на выставление ордеров и методы market увеличены, поэтому в качестве временного решения можете сделать собственную реализацию SL/TP, опираясь на текущую цену свечей или стакана.

**Comment by bikbulat2** [comment]
> Сейчас SL/TP еще нет, но лимиты на выставление ордеров и методы market увеличены, поэтому в качестве временного решения можете сделать собственную реализацию SL/TP, опираясь на текущую цену свечей или стакана.

Известны ли сроки?

**Comment by azalio** [comment]
Привет из июля 2021!

**Comment by sergeypesegov** [comment]
Шёл июль 2021, а SL/TP всё еще не появились. Ждём-с

**Comment by AlexanderVolkovTCS** [comment]
Сроки не называем, в новой версии API будет.

**Comment by 609i** [comment]
Просьба написать мне, тем кто разбирается в данной теме. Контакты в профиле.

**Comment by evsamsonov** [comment]
Ребята, подскажите, когда будет новая версия API. Писать на lua под quik это боль

**Comment by 0x100** [comment]
Up!

**Comment by 0x100** [comment]
Скоро 2 года будет заявке.

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, стоп-заявки реализованы в рамках нового API:
https://github.com/Tinkoff/investAPI
https://tinkoff.github.io/investAPI/stoporders/
