### ISSUE TITLE
Гарантируется ли порядок в streaming протоколе

### ISSUE THREAD

**Issue by olsh** [Tinkoff/invest-openapi#184]
Добрый день,

Не нашел информации о порядке событий в streaming. Гарантируется ли порядок событий для candles. https://tinkoffcreditsystems.github.io/invest-openapi/marketdata/#candlesubscribe

Например, может ли мне прийти свеча со временем меньшим чем свеча в предыдущем событии?

Наблюдал сегодня что вначале пришла свеча со временем 13:23:00, и сразу же после нее свеча 13:22:00

**Comment by Fatal1ty** [comment]
Могу точно сказать, что после переподключения можно точно получить свечку более раннюю.

**Comment by e673** [comment]
Тоже такое замечал - отслеживал по значению 'volume' - в пределах одной свечи оно должно непрерывно расти, но не всегда это происходит.

**Comment by NikitaMelnikov** [comment]
@necryin

**Comment by olsh** [comment]
Вопрос все еще актуален

**Comment by s-golikov** [comment]
@olsh , судя по моим тестам, порядок не гарантируется. Ловил по streaming api свечи с отставанием на несколько тиков.

**Comment by olsh** [comment]
> судя по моим тестам, порядок не гарантируется.

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, в общем случае порядок не гарантируется.
