### ISSUE TITLE
Некорректные данные в стакане через streaming-api

### ISSUE THREAD

**Issue by sergey-klochkov** [Tinkoff/invest-openapi#323]
Некорректные данные приходят в orderbook.
Для тикера HWM смотрю стакан в терминале и дебагером данные, которые приходят через StreamingEvent.Orderbook.
В терминале лучший аск 17.99 через StreamingEvent.Orderbook несколько минут подряд прилетают апдейты с аском 17.95

Такое же поведение сегодня замечал в тикерах LITE, LEVI, GS

Разве данные в стакане терминала и то, что отдается в стриминг-апи не должно совпадать?

**Comment by mlshvdv** [comment]
Аналогичная ситуация замечена с любыми акциями: и тех, что торгуется на Мосбирже, и на Спб.

Перед выставлением лимитного приказа подписываюсь на стакан и поступающие данные по стакану даже близко не стоят с реальными, которые можно видеть как в моб. приложении, так и в терминале. Приходиться пропускать N тиков, чтобы начали поступать какие-то более реальные данные совпадающие с теми, что в моб приложении и в терминале.

@NikitaMelnikov с чем это связано? Как можно устранить?

**Comment by NikitaMelnikov** [comment]
Добрый день, 

> Разве данные в стакане терминала и то, что отдается в стриминг-апи не должно совпадать?

Должны, разберемся почему не совпадают

**Comment by mkaynov** [comment]
аналогичная проблема. получаю цену по стрим, потом сразу же через рест. до нескольких секунд данные могут расходятся довольно сильно. Через рест приходит цена как в стакане мобильного приложения

                timestamp,             bid,   ask
stream: 1597435431835,     58.15,58.17
rest:      1597435431918,      57.25,58.33
stream: 1597435440200,     58.15,58.17
rest:      1597435440279,      57.25,58.33
stream: 1597435440844,     58.15,58.17
rest:      1597435440922,      57.25,58.33
stream: 1597435441534       58.15,58.17
rest:       1597435441609,     57.25,58.33

**Comment by mlshvdv** [comment]
@NikitaMelnikov добрый вечер! Проблема по-прежнему наблюдается и с ней не очень-то некомфортно работать. Есть ли какие-то изменения?

**Comment by finico** [comment]
Это уже очень давно. Писал про это в тикете #118 
Видимо, проблема где-то глубоко, раз до сих пор не исправили.
Ну либо и не пытались.

**Comment by NikitaMelnikov** [comment]
@mlshvdv @finico с проблематикой разобрались, нужно больше времени чтобы поправить, пока тяжело сказать сроки, так как исправление на нашей стороне довольно масштабное

**Comment by mlshvdv** [comment]
@NikitaMelnikov здорово, что стала ясна причина и ответ по срокам понятен, но со стороны клиентов убытки тоже могут быть довольно масштабными. Остается надеяться, что запланируете на ближайшее время исправление. Спасибо.

**Comment by NikitaMelnikov** [comment]
@mlshvdv 
Исправление запланировано и в работе, просто сроки очень растянуты :)

**Comment by sergey-klochkov** [comment]
@NikitaMelnikov есть ли какие-нибудь новости по исправлению?

**Comment by NikitaMelnikov** [comment]
@sergey-klochkov пока что нет, коллеги займутся задачей, но точные сроки не могу назвать

**Comment by BaryshevS** [comment]
https://github.com/TinkoffCreditSystems/invest-openapi/issues/552
Это ладно... там несколько очередей с данными и они в стакане суммируются..
Вот ты ставишь лимитку... на 100, цена уходить на 90 (т.е. ты готов платить на 10 выше рынка), а тебя не исполняют.
В поддержке оказалось, что там 2 очереди и вот ордер попал в ту, где таких заявок нет :)))))))))))))))))))))))))))))))))))
Минут через 30-40 исполнилось... И ладно была акция фиговая какая... Это была MSFT правда в вечернюю сессию, около 21:00, но все же.

вот ответ поддержки
28.04.2021, 12:25
Существует 2 пула ликвидности: Внутренний поток заявок - биржа СПБ. Внешний поток заявок - биржи NYSE и NASDAQ Если подать заявку до 14:30 (15:30 зимнее время), то она попадёт во внутренний пул ликвидности. После 14:30 (15:30 зимнее время) система проверяет, где условия исполнения заявки лучше. Она может попасть во внутренний или внешний пул ликвидности. В стакане отображаем заявки из обоих пулов ликвидности. Заявка, выставленная во внутреннем пуле, не может быть исполнена во внешнем пуле ликвидности и наоборот. Заявки на СПБ бирже сводятся по паритету. Порядок регистрации заявок на бирже не важен. Заявка на покупку или продажу сводится между инвесторами, которые выставили встречные заявки с подходящими условиями.

Вообще напоминает кухню forex

**Comment by opiumfive** [comment]
> #552 тикет закрыли, по этому копипасчу сюда. А то и не посмотрите.
> 
> Это ладно... там несколько очередей с данными и они в стакане суммируются..
> Вот ты ставишь лимитку... на 100, цена уходить на 90 (т.е. ты готов платить на 10 выше рынка), а тебя не исполняют.
> В поддержке оказалось, что там 2 очереди и вот ордер попал в ту, где таких заявок нет :)))))))))))))))))))))))))))))))))))
> Минут через 30-40 исполнилось... И ладно была акция фиговая какая... Это была MSFT правда в вечернюю сессию, около 21:00, но все же.
> 
> вот ответ поддержки
> 28.04.2021, 12:25
> Существует 2 пула ликвидности: Внутренний поток заявок - биржа СПБ. Внешний поток заявок - биржи NYSE и NASDAQ Если подать заявку до 14:30 (15:30 зимнее время), то она попадёт во внутренний пул ликвидности. После 14:30 (15:30 зимнее время) система проверяет, где условия исполнения заявки лучше. Она может попасть во внутренний или внешний пул ликвидности. В стакане отображаем заявки из обоих пулов ликвидности. Заявка, выставленная во внутреннем пуле, не может быть исполнена во внешнем пуле ликвидности и наоборот. Заявки на СПБ бирже сводятся по паритету. Порядок регистрации заявок на бирже не важен. Заявка на покупку или продажу сводится между инвесторами, которые выставили встречные заявки с подходящими условиями.
> 
> Вообще напоминает кухню forex

Это абсолютно нормальное поведение.

**Comment by AlexanderVolkovTCS** [comment]
@BaryshevS Вам все верно сказали: механизм двух пулов реализован не у нас, он реализован на **СПБ бирже** и у всех брокеров, работающих с СПБ, механизм выставления будет тот же самый.

**Comment by nonamegithub** [comment]
> механизм двух пулов реализован не у нас

У меня есть подозрения, что вы такую же схему реализовали у себя. Стакан по подписке выдает вас с головой: периодически, как я понимаю, он показывает внутренний пул заявок. Если нет, потрудитесь объяснить мне недалекому, откуда и какие данные он показывает в моменты, когда рассинхронизирован с rest-стаканом?  Возьмем для примера Магнит: он что, тоже на СПБ бирже торгуется? Регулярно наблюдаю стаканы по подписке с меньшим количеством заявок, чем в полноценном стакане. И упаси боже в такой момент выставить заявку на продажу или покупку по рынку: только вам одним известно, заявками из какого стакана (пула ликвидности, в нашем случае) вы ее закроете...

**Comment by mlshvdv** [comment]
У тикета скоро день рождения — ему исполнится год.
@AlexanderVolkovTCS планируется ли исправление ситуации?

**Comment by AlexanderVolkovTCS** [comment]
@mlshvdv текущая версия не поддерживается, в новой - исправлено.

**Comment by BaryshevS** [comment]
> @mlshvdv текущая версия не поддерживается, в новой - исправлено.

А как можно подключиться к новому эндпоинту в рамках альфы/беты?

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, рекомендуем переходить на новый api -  https://github.com/Tinkoff/investAPI/
