### ISSUE TITLE
Информация о возможности шорта

### ISSUE THREAD

**Issue by pbeschetnov** [Tinkoff/invest-openapi#385]
Привет!

Никак не могу найти в документации каким образом для определенной бумаги понять, возможна ли сделка шорт. А также сколько лотов доступны в шорт.
Подскажите, пожалуйста.

Создавать реальную операцию продажи, чтобы понять шортится ли акция, не вариант, так как на это тратятся деньги :)

**Comment by NikitaMelnikov** [comment]
В данный момент такого метода нет

**Comment by pbeschetnov** [comment]
Такая фича была бы очень полезна, так как не придется торговать вслепую.
Количество доступных акций в лонг можно посчитать по размеру средств в аккаунте, тогда как число доступных акций в шорт высчитывается только на бэкендах платформы инвестиций.

**Comment by morvan1980** [comment]
Поддержу автора. Такая возможность очень необходима. Живем в 21 веке и руками добавлять инфу что акция шортится не годится.

**Comment by AlexanderVolkovTCS** [comment]
Добрый день! 
Старая версия API дорабатываться не будет, в новой API (https://github.com/Tinkoff/investAPI/) в инструментах есть отдельный признак short_enabled_flag.
