### ISSUE TITLE
Список фьючерсов

### ISSUE THREAD

**Issue by VasyaSmolyar** [Tinkoff/invest-openapi#501]
Ни в SDK, ни в API нет метода получения списка доступных фьючерсов. Хотелось бы расширения API и на фьючерсы

**Comment by oksidisko** [comment]
Есть тут планы/подвижки? Терминал поддерживает фьючи, приложение тоже, а в списке операций через API их нет, это как-то неконсистентно выглядит.

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, поддержка фьючей будет, в процессе, сроки не называем.

**Comment by mlshvdv** [comment]
@AlexanderVolkovTCS Александр, уточните, пожалуйста: поддержка фьючерсов будет в текущей версии openapi или уже в следующей?

**Comment by ssolarevIDBS** [comment]
Очень хочется поддержку фьючерсов. Ждем с нетерпением. Надеюсь она будет встроена в текущий API .

**Comment by AlexanderVolkovTCS** [comment]
Только в следующей, в текущей не будет точно, к сожалению

**Comment by Blucknote** [comment]
Добавьте так же, пожалуйста отображение вариационной маржи в операциях `/operations`

**Comment by Pykhto** [comment]
А в следующей, это в какой? В декабре новая версия вышла - функция появилась?

**Comment by Pykhto** [comment]
В декабре вышла очередная версия, функции так до сих пор нет?

**Comment by tumb1er** [comment]
https://tinkoff.github.io/investAPI/instruments/#futures а Вы доку смотрели?

**Comment by AlexanderVolkovTCS** [comment]
Как писал ранее, в старой версии поддержки фьючерсов не будет, только в новой.
но для удобства клиентов реализовали и проксирование методов новой api в REST: https://tinkoff.github.io/investAPI/swagger-ui/
https://github.com/Tinkoff/investAPI
