### ISSUE TITLE
dealer_normal_trading

### ISSUE THREAD

**Issue by sergeymavrin** [Tinkoff/invest-openapi#647]
Подскажите что значит статус у бумаги dealer_normal_trading?
Можете привести весь возможный список статусов с их пояснением? Спасибо.

**Comment by polkila** [comment]
https://github.com/TinkoffCreditSystems/invest-openapi/issues/387

**Comment by AlexanderVolkovTCS** [comment]
https://tinkoff.github.io/invest-openapi/marketdata/#trade_status
