### ISSUE TITLE
Метод получения индикаторов

### ISSUE THREAD

**Issue by vladikKBR85** [Tinkoff/invest-openapi#650]
Добрый день. Подскажите пожалуйста

1) Нам необходим способ обращения к значениям индикаторов на заданную метку времени. Затрудняемся найти в документации.

2) При запросе данных по свечам - в ответе время приходит UTC+4. Это корректно?

**Comment by vladik-dev** [comment]
Коллеги?

**Comment by polkila** [comment]
> 1. Нам необходим способ обращения к значениям индикаторов на заданную метку времени. Затрудняемся найти в документации.

Постройте сами, в азе брокера не хранятся индикаторы. Подсмотреть можете здесь:
https://code.highcharts.com/stock/indicators/indicators.src.js
https://code.highcharts.com/stock/indicators/ema.src.js
https://code.highcharts.com/stock/indicators/macd.src.js
https://code.highcharts.com/stock/indicators/supertrend.src.js

**Comment by AlexanderVolkovTCS** [comment]
>Нам необходим способ обращения к значениям индикаторов
В api нет индикаторов и пока не планируется

>UTC+4. Это корректно?
Вероятно, у вас sdk или обертки время преобразуют.
