### ISSUE TITLE
market.market_candles_get выдает 503-ю ошибку на получение свечей облигации FreedomFinance

### ISSUE THREAD

**Issue by irishrover** [Tinkoff/invest-openapi#653]
```
Exception has occurred: ApiException       (note: full exception trace is shown but execution is paused at: <module>)
(500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'Server': 'nginx', 'Date': 'Thu, 30 Dec 2021 12:30:07 GMT', 'Content-Type': 'application/json', 'Content-Length': '150', 'Cache-Control': 'no-store, no-cache, must-revalidate', 'access-control-allow-origin': '*', 'access-control-allow-headers': 'accept, content-type, authorization, access-control-allow-headers, x-requested-with', 'access-control-allow-methods': 'GET,HEAD,POST,DELETE,OPTIONS,PUT,PATCH', 'x-edge-processing-time': '17'})
HTTP response body: {"trackingId":"fd1.....cc","payload":{"message":"[figi]: Instrument not found by figi=BBG00RMFNJQ7","code":"VALIDATION_ERROR"},"status":"Error"}
```

При этом
1) этой облигации нет и в запросе на портфель
2) на сайте и в приложении она видна.

**Comment by irishrover** [comment]
Проблема все еще актуальна.

**Comment by irishrover** [comment]
В новом API, которое работает через grpc проблема не наблюдается.

**Comment by SinnerUfa** [comment]
Здравствуйте, вопрос к администраторам, возможно несколько не по теме, API на gRPC уже полноценно запущен? Находил только документацию на https://tinkoff.github.io/investAPI/grpc/.
Ссылка на документацию из личного кабинета на текущий момент ведет на https://tinkoff.github.io/invest-openapi/.
Спасибо заранее за ответ.

**Comment by irishrover** [comment]
> Здравствуйте, вопрос к администраторам, возможно несколько не по теме, API на gRPC уже полноценно запущен? Находил только документацию на https://tinkoff.github.io/investAPI/grpc/. Ссылка на документацию из личного кабинета на текущий момент ведет на https://tinkoff.github.io/invest-openapi/. Спасибо заранее за ответ.

Я пока пробовал не очень много. Работает вроде, из неудобного: при получении портфеля нет названий активов, а только есть их FIGI.

**Comment by irishrover** [comment]
> BBG00RMFNJQ7

https://cbonds.ru/bonds/663671/
А здесь другой FIGI. И эта бумага исчезла из двух моих портфелей (БС и ИИС) по запросу  через OpenAPI.

**Comment by irishrover** [comment]
Прошу переоткрыть Issue.

**Comment by AlexanderVolkovTCS** [comment]
>А здесь другой FIGI.
Идентификация инструментов в Тинькофф может не совпадать с другими ресурсами.

Более того, старая версия openapi не работает с инструментами, например выведенными из обращения

Для получения списка доступных инструментов пользуйтесь методами https://tinkoff.github.io/invest-openapi/swagger-ui/#/market/get_market_bonds в старой версии и [Bonds ](https://tinkoff.github.io/investAPI/instruments/#bonds) в новой.

А первый выпуск облигаций Freedom Finance имеет figi/isin BBG00N9S8LL0/RU000A1003N7

**Comment by irishrover** [comment]
> > А здесь другой FIGI.
> > Идентификация инструментов в Тинькофф может не совпадать с другими ресурсами.
> 
> Более того, старая версия openapi не работает с инструментами, например выведенными из обращения
> 
> Для получения списка доступных инструментов пользуйтесь методами https://tinkoff.github.io/invest-openapi/swagger-ui/#/market/get_market_bonds в старой версии и [Bonds ](https://tinkoff.github.io/investAPI/instruments/#bonds) в новой.
> 
> А первый выпуск облигаций Freedom Finance имеет figi/isin BBG00N9S8LL0/RU000A1003N7

Хорошо, но почему эта бумага больше не возвращается из Api?

**Comment by AlexanderVolkovTCS** [comment]
Возвращается. И в старой апи тоже:
      {
        "figi": "BBG013J0LT31",
        "ticker": "RU000A1040E8",
        "isin": "RU000A1040E8",
        "minPriceIncrement": 0.001,
        "faceValue": 1000,
        "lot": 1,
        "currency": "USD",
        "name": "Freedom Finance",
        "type": "Bond"
      },

**Comment by AlexanderVolkovTCS** [comment]
>В текущей редакции API gRPC уже может использоваться для совершения операций;

да

>Кодогенерация клиентской части оставлена на клиента или будет какое то подобие SDK lдля различных языковых платформ (наподобие REST и/или в качестве примера);

SDK пока в процессе разработки

>И какие ориентировочные сроки полного перехода на gRPC (когда перестанет работать текущий API).

По мере миграции клиентов на новую версию. Примерно полгода.

>Еще раз заранее спасибо за ответы.

Вам спасибо за интерес к api, обращайтесь, если будут вопросы)

**Comment by irishrover** [comment]
> Возвращается. И в старой апи тоже:
> 
> ```
>     "figi": "BBG00N9S8LL0",
>     "ticker": "RU000A1003N7",
>     "isin": "RU000A1003N7",
>     "minPriceIncrement": 0.1,
>     "faceValue": 1000,
>     "lot": 1,
>     "currency": "RUB",
>     "name": "Фридом Финанс выпуск 1",
>     "type": "Bond"
> ```

Спасибо. А вы можете проверить облигацию с тикером RU000A101CG5? У меня проблема с ней и старым API.

**Comment by AlexanderVolkovTCS** [comment]
Уточните, она у вас есть в портфеле?

**Comment by irishrover** [comment]
> Уточните, она у вас есть в портфеле?

Да. 10 штук на БС и 1 на ИИС.
Они отображаются в приложении, в новом API, на сайте, но не в старом API.

**Comment by irishrover** [comment]
Еще из странного: страница бумаги тоже не работает - https://www.tinkoff.ru/invest/not-found/RU000A101CG5/

**Comment by irishrover** [comment]
Прикладываю trackingId:

`HTTP response body: {"trackingId":"6ea4b807d2eb8521","payload":{"message":"[figi]: Instrument not found by figi=BBG00RMFNJQ7","code":"VALIDATION_ERROR"},"status":"Error"}`

**Comment by AlexanderVolkovTCS** [comment]
>Еще из странного: страница бумаги тоже не работает 
Это потому, что бумагу исключили из списков доступных - она исчезает и с сайта и с апи.

Для получения валидного портфеля рекомендую пользоваться второй версией.

**Comment by irishrover** [comment]
> > Еще из странного: страница бумаги тоже не работает
> > Это потому, что бумагу исключили из списков доступных - она исчезает и с сайта и с апи.
> 

А как и почему ее исключили из списка доступных? Я же ее вижу на сайте, я могу ее продать и купить, стакан жив. А где уведомление про это?

> Для получения валидного портфеля рекомендую пользоваться второй версией.

Это в планах, но так сразу я не могу переделать кучу кода на нее. Тем более, что еще в конце декабря все работало.
