### ISSUE TITLE
candle:subscribe - очень мало уведомлений

### ISSUE THREAD

**Issue by ZaValera** [Tinkoff/invest-openapi#657]
Этот вопрос уже задавался, но немного в другом ключе, и на него так и не последовало ответа.

Как часто приходят сообщения по этой подписке?
На практике, например у AAPL, во время активной торговой сессии приходит 10 - 12 сообщений.
В то время как в web-терминале аналогичные сообщения льются рекой, по несколько сообщений в секунду.

В openapi этот показатель явно зарезан, вероятно для снижения нагрузки. Есть ли возможность снять это ограничение и получать весь поток данных?

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, в новой версии API поток данных с рыночными котировками более производительный, рекомендую перейти:  https://github.com/Tinkoff/investAPI

> во время активной торговой сессии приходит 10 - 12 сообщений.

Но это аномалия, в какое время подписывались и по какому интервалу?

**Comment by ZaValera** [comment]
> Но это аномалия, в какое время подписывались и по какому интервалу?

Время 17:45 по Москве - как раз начались торги на NASDAQ.
Интервал `1min`, но какое это имеет отношение к проблеме? Интервал не должен никак влиять на количество сообщений, только на данные в свече.

В таблице ниже собраны данные, которые приходили по подписке.
Видно, что за одну минуту приходит 11-12 свечей.
<img width="490" alt="image" src="https://user-images.githubusercontent.com/6653538/150548333-64992de8-8afa-47ca-96ee-7260e546e11f.png">

**Comment by ZaValera** [comment]
> ...рекомендую перейти: https://github.com/Tinkoff/investAPI

Ещё б там нормальная инструкция была, как это всё подключить на популярных языках.
Воспользовался этим [туториалом](https://grpc.io/docs/languages/node/basics/), ничего не взлетело.
