### ISSUE TITLE
Тормозит portfolio

### ISSUE THREAD

**Issue by DiktatorDNS3018** [Tinkoff/invest-openapi#658]
Жутко тормозит запрос портфеля.
На один запрос портфеля уходит 10-20 секунд, в портфеле всего 139 позиций. При этом ордера, которых 200+, грузятся за 3 секунды, а список из 3000+ операций грузится за 2 секунды.
К лимиту в 120 запросов в минуту и близко не приближаюсь, если бы всё работало идеально, то выходило бы до 40 запросов портфеля в минуту, а в такие периоды их от силы 5. 
Наблюдаю такую ситуацию почти каждую неделю, а иногда каждый день, и это сильно мешает нормальной работе.

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, был инцидент, сейчас должно работать лучше.
Рекомендую переходить на вторую версию API: https://github.com/Tinkoff/investAPI
