### ISSUE TITLE
Пояснение к типам операций

### ISSUE THREAD

**Issue by DmitryTsybulkin** [Tinkoff/invest-openapi#659]
Здравствуйте!
Объясните, пожалуйста, значение перечисленных типов операций (В сваггере это класс: `OperationTypeWithCommissionstring`): 

1. Buy, 
2. BuyCard, 
3. Sell, 
4. BrokerCommission, 
5. ExchangeCommission, 
6. ServiceCommission, 
7. MarginCommission, 
8. OtherCommission, 
9. PayIn, 
10. PayOut, 
11. Tax, 
12. TaxLucre, 
13. TaxDividend, 
14. TaxCoupon, 
15. TaxBack, 
16. Repayment, 
17. PartRepayment, 
18. Coupon, 
19. Dividend, 
20. SecurityIn, 
21. SecurityOut

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, https://tinkoff.github.io/investAPI/operations/#operationtype
