### ISSUE TITLE
Ошибка tinvest.exceptions.UnexpectedError: 500 {"trackingId":"dba85b244643578b","payload":{"message":"Unknown account"

### ISSUE THREAD

**Issue by ga232321** [Tinkoff/invest-openapi#664]
Ошибка возникает при попытки взаимодействия client
![image](https://user-images.githubusercontent.com/88882833/152841767-e2210c46-2fca-4ebe-8276-d69f1adf8700.png)

**Comment by ga232321** [comment]
Ребят, надеюсь на вашу помощь

**Comment by AlexanderVolkovTCS** [comment]
Добрый вечер, вы используете контур с песочницей (sandbox=true), а в ней вначале надо создать счет методом https://tinkoff.github.io/invest-openapi/swagger-ui/#/sandbox/post_sandbox_register.

если вам надо получить реальное портфолио, то ставьте use_sandbox=false

**Comment by ga232321** [comment]
Не могли бы вы пожалуйста уточнить поподробнее, что и где нужно исправить/дописать, для "чайника"...?Заранее спасибо!

**Comment by ga232321** [comment]
> Добрый вечер, вы используете контур с песочницей (sandbox=true), а в ней вначале надо создать счет методом https://tinkoff.github.io/invest-openapi/swagger-ui/#/sandbox/post_sandbox_register.
> 
> если вам надо получить реальное портфолио, то ставьте use_sandbox=false



> Добрый вечер, вы используете контур с песочницей (sandbox=true), а в ней вначале надо создать счет методом https://tinkoff.github.io/invest-openapi/swagger-ui/#/sandbox/post_sandbox_register.
> 
> если вам надо получить реальное портфолио, то ставьте use_sandbox=false

Не могли бы вы пожалуйста уточнить поподробнее, что и где нужно исправить/дописать, для "чайника"...? Заранее спасибо!
