### ISSUE TITLE
Запросы начали падать с CORS ошибкой

### ISSUE THREAD

**Issue by EJohnF** [Tinkoff/invest-openapi#665]
Здравствуйте.

А в последние дни(неделю) что то изменилось в настройках CORS? Раньше веб-приложение нормально работало, а сейчас запросы падают

Access to XMLHttpRequest at 'https://api-invest.tinkoff.ru/openapi/portfolio' from origin 'https://***.herokuapp.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by AlexanderVolkovTCS** [comment]
CORS наблюдался для неработающего токена.

Проверьте, пожалуйста, токен на сваггере  https://tinkoff.github.io/invest-openapi/swagger-ui/ и если он точно рабочий, то переоткройте тикет.
