### ISSUE TITLE
Запросы падают с CORS

### ISSUE THREAD

**Issue by EJohnF** [Tinkoff/invest-openapi#666]
Переоткрываю тикет (на swagger проверил токен - работает + серверное приложение с тем же токеном тоже работает):

Здравствуйте.

А в последние дни(неделю) что то изменилось в настройках CORS? Раньше веб-приложение нормально работало, а сейчас запросы падают

Access to XMLHttpRequest at 'https://api-invest.tinkoff.ru/openapi/portfolio' from origin 'https://***.herokuapp.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by AlexanderVolkovTCS** [comment]
исправлено.
