### ISSUE TITLE
OpenApi v1 streaming protocol (via websocket) Getting error code = 403 while connection

### ISSUE THREAD

**Issue by Sergio1C** [Tinkoff/invest-openapi#668]
Hi there. I have already been using streaming connection a long time (a year) and all were working, but currently I can't connect for some reason (I am getting 301 error instead of 101, please see the screen I attached):

![image](https://user-images.githubusercontent.com/18114872/160106371-298703e1-d975-4bda-b5d8-48a2e067b79e.png)

More context: I use .Net framewok standard webscoket. Also I refers to your API example and use the same approach (passing token in the request header & use the same Url connection). See here: https://tinkoff.github.io/invest-openapi/marketdata/

Can you explain is it a known issue? How can I overcome this issue? Is there any change from your side that I need to know to resolve my issue? Thank you in advance.

**Comment by AlexanderVolkovTCS** [comment]
Вероятно, за это время токен стал невалидным. 
Попробуйте перевыпустить токен.
