### ISSUE TITLE
Rest запрос к portfolio

### ISSUE THREAD

**Issue by George70-svg** [Tinkoff/invest-openapi#671]
Добрый день. Попытался получить данные своего портфеля из openAPI для приложения на vue. Столкнулся с проблемами CORS. Есть ли возможность это исправить и как-то получить данные своего портфеля? Т.е. хочется понять возможно ли вообще получать данные из браузерного приложения или CORS не даст этого сделать? Потому что пробовал через node js, данные приходят, но это не то, что мне нужно.

![image](https://user-images.githubusercontent.com/62888915/162926917-1ddc06e0-b8d8-483e-ad52-10e30b035b0f.png)

```
import axios from "axios";

const TOKEN = 'xxx'

const instance = axios.create({
    baseURL: 'https://api-invest.tinkoff.ru/openapi/',
    //withCredentials: true,
    headers: {
        'Authorization': `Bearer ${TOKEN}`,
        'accept': 'application/json',
        //'Access-Control-Allow-Origin': 'https://tinkoff.github.io/invest-openapi'
    }
})

export const getData = () => {
    return instance.get("portfolio")
        .then(response => {
            console.log(response);
        })
}
````

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, рекомендуем переходить на новую версию API: https://github.com/Tinkoff/investAPI/
