### ISSUE TITLE
Странная отработка рыночных ордеров

### ISSUE THREAD

**Issue by Maxim-Fil** [Tinkoff/invest-openapi#677]
Столкнулся с проблемой по бумагам в USD (в RUB вроде не наблюдается).
Рыночные ордера в SANDBOX исполняются по ценам, крайне далеким от рынка.

На пример 05.07.2022:
выставил заявку на покупку PBF при последней цене 28.42, исполнение прошло по 30.6 (возникла мысль, что стакан оказался пустой, ну мало ли).

Следом было две сделки по MSTR, покупка при последней цене по рынку 173.42, исполнилась по цене 165.59 и далее через пол часа продажа при цене по рынку 176.59 - исполнение прошло по ТОЙ ЖЕ цене, что и покупка 165.59.

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, рекомендуем переходить на новую версию API https://github.com/Tinkoff/investAPI/
Старая не будет поддерживаться.
