### ISSUE TITLE
Узнать через API доступен ли инструмент для покупки или шорта

### ISSUE THREAD

**Issue by IvanIvanov1985** [Tinkoff/invest-openapi#678]
Добрый день. Есть ли старой версии в http API возможность узнать, не заблокирован ли конкретный тикер для покупки и можно ли его шортить? Сходу в доках не нашёл.

И ещё по поводу прекращения поддержки старой версии API - написано что прекращается в 2022 году. Сейчас известно в какую дату прекратится поддержка, чтобы понимать какой дедлайн разработки по переезду на grpc?

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, в старой версии - нет, рекомендуем использовать новую, в ней все эти флаги есть.
Отключить планируется 31.12.2022, но рекомендуем перейти раньше.

>на grpc

также отмечу, что в новой версии есть rest-прокси
