### ISSUE TITLE
streaming протокол, не достаточность данных

### ISSUE THREAD

**Issue by BaryshevS** [Tinkoff/invest-openapi#681]
"SECID": "SU26240RMFS0",
"VALTODAY_RUR": 1076819856,

это данные с биржи по обороту в рублях
https://iss.moex.com/iss/engines/stock/markets/bonds/securities.json

В тинькофф по этому инструменту оборот в рублях 391 967 924, -  39% от реальных.

Все что было отправлено через вебсокет по инструменту.
Бывают разрывы, но не в течение 10 секунд делается реконнект. т.к. понимаю потерю до 10% данных, но не 60%

@AlexanderVolkovTCS

**Comment by AlexanderVolkovTCS** [comment]
Старый api в первом квартале выйдет из эксплуатации, рекомендуем переходить на новую https://github.com/Tinkoff/investAPI/
