### ISSUE TITLE
Значение НКД в ответе метода `/portfolio`

### ISSUE THREAD

**Issue by maksim77** [Tinkoff/invest-openapi#83]
Предлогаю в ответе метода `/portfolio` добавить информацию о НКД в явном виде.

Сейчас эту информацию можно получить вычитая значения `averagePrice` но мне кажется это не очень удобно/логично.

**Comment by HiHat** [comment]
Согласен!
Очень не логично, что _текущий_ НКД добавляется в averagePositionPrice _покупок_ и чтобы его подсчитать надо из averagePositionPrice вычесть averagePositionPriceNoNkd!
НКД надо отдельно выдавать!

**Comment by HiHat** [comment]
Теперь вообще пропал НКД...
https://github.com/Tinkoff/invest-openapi/issues/644
